---
- name: Check and apply available updates on Debian type Linux
  hosts: "{{ deb_hosts }}"

  tasks:

  - name: Make sure Aptitude in installed
    apt:
      name: aptitude
      state: latest

  - name: Apt update
    apt:
      update-cache: yes

  - name: Check updates
    apt:
      upgrade: yes
    check_mode: yes
    register: output

  - name: Print available updates
    debug:
      var: output
