---
- name: Check and apply available updates on Debian type Linux
  hosts: "{{ deb_hosts }}"
  serial: 1

  tasks:

  - name: Make sure Aptitude in installed
    apt:
      name: aptitude
      state: latest

  - name: Apt update
    apt:
      update-cache: yes
    register: update

  - name: Check updates
    apt:
      upgrade: 'yes'
    check_mode: yes
    register: output

  - name: Print available updates
    debug:
      var: output.msg

  - name: Print message if no update available
    debug:
      msg: "No update available"
    when: "No packages will be installed, upgraded, or removed." in output.msg
