---
- name: Check and apply available updates on Debian type Linux
  hosts: "{{ deb_hosts }}"

  tasks:

  - name: Make sure Aptitude in installed
    apt:
      name: aptitude
      state: latest

  - name: Apt update
    apt:
      update-cache: yes
      force_apt_get: yes
    register: update

  - name: Print available updates
    debug:
      var: update

  - name: Check updates
    apt:
      upgrade: 'yes'
    check_mode: yes
    register: upgrade

  - name: Print available updates
    debug:
      var: upgrade
