---
- name: Add DNS entry for named
  hosts: "{{ dns_srv }}"

  tasks:

  - name: Add DNS A entry
    lineinfile:
      line: "{{ new_host }}. IN A {{ ip_add }}"
      path: "/var/named/dynamic/db.{{ new_host.split('.', 1)[1] }}"
      state: present
    notify:
    - Restart named

  - name: Add DNS PTR entry
    lineinfile:
      line: "{{ ip_add.split('.')[3] }} IN PTR {{ new_host }}."
      path: "/var/named/dynamic/db.{{ ip_add.split('.')[2] }}.{{ ip_add.split('.')[1] }}.{{ ip_add.split('.')[0] }}.in-addr.arpa"
      state: present
    notify:
    - Restart named

  handlers:

  - name: Restart named
    service:
      name: named
      state: restarted
