---
- name: Add DNS entry for named
  hosts: "{{ dns_srv }}"

  tasks:

  - name: Add DNS A entry
    lineinfile:
      line: "{{ clt_fqdn }}. IN A {{ clt_ipadd }}"
      path: "/var/named/dynamic/db.{{ clt_fqdn.split('.', 1)[1] }}"
      state: present
    notify:
    - Restart named

  - name: Add DNS PTR entry
    lineinfile:
      line: "{{ clt_ipadd.split('.')[3] }} IN PTR {{ clt_fqdn }}."
      path: "/var/named/dynamic/db.{{ clt_ipadd.split('.')[2] }}.{{ clt_ipadd.split('.')[1] }}.{{ clt_ipadd.split('.')[0] }}.in-addr.arpa"
      state: present
    notify:
    - Restart named

  handlers:

  - name: Restart named
    service:
      name: named
      state: restarted
