---
- name: Remove DNS entry for libvirt dnsmasq
  hosts: "{{ dns_srv }}"

  tasks:

  - name: Remove DNS entry
    lineinfile:
      regexp: "{{ decom_host }}"
      path: "/etc/hosts"
      state: absent
    notify:
    - Restart libvirt

  handlers:

  - name: Restart libvirt
    service:
      name: libvirtd
      state: restarted
