---
- name: Remove DNS entry for named
  hosts: "{{ dns_srv }}"

  tasks:

  - name: Remove DNS A entry
    lineinfile:
      regexp: "{{ decom_host }}"
      path: "/var/named/dynamic/db.{{ decom_host.split('.', 1)[1] }}"
      state: absent
    notify:
    - Restart named

  - name: Remove DNS PTR entry
    lineinfile:
      regexp: "{{ decom_host }}"
      path: "/var/named/dynamic/db.*.in-addr.arpa"
      state: absent
    notify:
    - Restart named

  handlers:

  - name: Restart named
    service:
      name: named
      state: restarted
