---
- name: Add DNS entry for libvirt dnsmasq
  hosts: "{{ dns_srv }}"

  tasks:

  - name: Add DNS entry
    lineinfile:
      line: "{{ clt_ipadd }} {{ clt_fqdn }} {{ clt_name }}"
      path: "/etc/hosts"
      state: present
    notify:
    - Restart libvirt

  - name: Restart libvirt
    service:
      name: libvirtd
      state: restarted
