---
- name: Remove DNS entry for libvirt dnsmasq
  hosts: "{{ dns_srv }}"

  tasks:

  - name: Remove DNS entry
    lineinfile:
      line: "{{ decom_host_ip }} {{ decom_host }} {{ decom_host.split('.')[0] | lower }}"
      path: "/etc/hosts"
      state: absent
    notify:
    - Restart libvirt

  handlers:

  - name: Restart libvirt
    service:
      name: libvirtd
      state: restarted
