---
- name: Check available updates on Enterprise Linux servers
  hosts: all

  tasks:

  - name: Check available updates
    yum:
      list: updates
    register: output

  - name: Print message if no update available
    debug:
      msg: "System is up to date."
    when: output.results|length == 0

  - name: Print available updates
    debug:
      var: output.results
    when: output.results|length > 0
