---
- name: Create a Foreman host
  hosts: localhost

  tasks:

  - name: Create a host
    theforeman.foreman.foreman_host:
      username: "{{ fman_usr }}"
      password: "{{ fman_pwd }}"
      server_url: "{{ fman_url }}"
      validate_certs: no
      name: "{{ new_host }}"
      hostgroup: "{{ hostgroup }}"
      state: present
