---
- name: Create a Foreman host
  hosts: "{{ fman_srv }}"

  tasks:

  - name: Create a host
    command: "/usr/bin/hammer -u {{ fman_usr }} -p {{ fman_pwd }} host create --build true --compute-attributes start=1 --hostgroup {{ hostgroup }} --organization {{ organization }} --location {{ location }} --ip {{ ip_add }} --name {{ new_host }}"
