- name: Initialization of localhost to be able to use the different playbooks
  hosts: localhost

  tasks:

  - name: Print current version of Python and Ansible
    debug:
      msg:
      - "Ansible version: {{ ansible_version.full }}"
      - "Python version: {{ ansible_python_version }}"

  - name: Install python dependancies
    pip:
      name:
        - PyYAML
        - apypie
        - mazer

  - name: Install Foreman collection from Ansible Galaxy
    command: mazer install theforeman.foreman
    register: output

  - name: Print output of installation from Ansible Galaxy
    debug:
      var: output
