- name: Initialization of localhost to be able to use the different playbooks
  hosts: localhost

  tasks:

  - name: Add foreman-client repository
    yum_repository:
      name: foreman-client
      description: Foreman client latest
      baseurl: http://yum.theforeman.org/client/latest/el7/$basearch/

  - name: Print current version of Python and Ansible
    debug:
      msg:
      - "Ansible version: {{ ansible_version.full }}"
      - "Python version: {{ ansible_python_version }}"

  - name: Install python dependancies
    pip:
      name:
        - PyYAML
        - apypie
        - mazer

  - name: Install Foreman collection from Ansible Galaxy
    command: mazer install theforeman.foreman
    register: output

  - name: Print output of installation from Ansible Galaxy
    debug:
      var: output
