- name: Initialization of localhost to be able to use the different playbooks
  hosts: localhost

  tasks:

  - name: Add foreman-client repository
    yum_repository:
      name: foreman-client
      description: Foreman client latest
      baseurl: http://yum.theforeman.org/client/latest/el7/$basearch/

  - name: Install ansible-collection-theforeman-foreman package
    yum:
      name: ansible-collection-theforeman-foreman
      disable_gpg_check: yes
      state: latest
