---
- name: Check and apply available updates on Enterprise Linux servers
  hosts: "{{ el_hosts }}"
  serial: 1

  tasks:

  - name: Check available updates
    yum:
      list: updates
    register: output

  - name: Print message if no update available
    debug:
      msg: "System is up to date."
    when: output.results|length == 0

  - name: Print available updates
    debug:
      var: output | json_query('results[].name') | unique
    when: output.results|length > 0

  - name: Print message if restart required
    debug:
      msg: "Restart required."
    when: '"kernel" in output | json_query("results[].name") | unique | join("|")'

  - name: Update server
    block:
  
    - name: Update all RPM
      yum:
        name: '*'
        state: latest
  
    - name: Reboot server if needed
      reboot:
      when: '"kernel" in output | json_query("results[].name") | unique | join("|")'
    
    when: output.results|length > 0
  
    rescue:

    - name: "Print error message"
      debug:
        msg: "Error while update packages, please check the server's configuration."
