" vim documentation: options
" Retrieved from
" http://vimdoc.sourceforge.net/htmldoc/options.html

" Options and short names:
" autoindent     ai    auto indentation
" cursorcolumn   cuc   highlight current column
" expandtab      et    replace tab by spaces
" number         nu    display line number
" shiftwidth     sw    nb of spaces to use for autoindent
" tabstop        ts    nb of spaces that a tab counts for
" textwidth      tw    set max line length

" General settings
set nu et ai
color desert

" Puppet manifests files
au BufNewFile,BufRead *.pp setf puppet
au FileType puppet setlocal ts=2 sw=2 cuc

" Python files
au FileType python setlocal ts=4 sw=4 cuc

" Shell files
au FileType sh setlocal ts=2 sw=2 cuc

" Yaml files
au FileType yaml setlocal ts=2 sw=2 cuc

" Go to VIM directory:
" cd $(vim -Nesc '!echo $VIMRUNTIME' -c qa)
" List all FileTypes:
" find syntax ftplugin -iname '*.vim' -exec basename -s .vim {} + | sort -u
